parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - "plugin:@typescript-eslint/recommended"
  - next/core-web-vitals
  - prettier
plugins:
  - "@typescript-eslint"
  - prettier
root: true
rules:
  no-console: "warn"
  prettier/prettier: 2
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      natural: false
