# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-unit-tests:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env
      - name: Run lint
        run: npm run lint
      - name: Run unit tests
        run: npm test
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './integration-tests/docker-compose.yml'
      - name: Migrate and seed the test database
        run: npm run ci:db:reset
      - name: Run integration tests
        run: npm run test:ci
